#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpireAlert
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SDV7")]
	public partial class sdv7DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGsp_shouying_qyshb(Gsp_shouying_qyshb instance);
    partial void UpdateGsp_shouying_qyshb(Gsp_shouying_qyshb instance);
    partial void DeleteGsp_shouying_qyshb(Gsp_shouying_qyshb instance);
    #endregion
		
		public sdv7DataContext() : 
				base(global::ExpireAlert.Properties.Settings.Default.SDV7ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public sdv7DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sdv7DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sdv7DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public sdv7DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gsp_shouying_qyshb> Gsp_shouying_qyshbs
		{
			get
			{
				return this.GetTable<Gsp_shouying_qyshb>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gsp_shouying_qyshb")]
	public partial class Gsp_shouying_qyshb : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _xuhao;
		
		private string _daima;
		
		private string _mingcheng;
		
		private string _dizhi;
		
		private string _dianhua;
		
		private System.Nullable<System.DateTime> _youxiao_rq_xk;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnxuhaoChanging(int value);
    partial void OnxuhaoChanged();
    partial void OndaimaChanging(string value);
    partial void OndaimaChanged();
    partial void OnmingchengChanging(string value);
    partial void OnmingchengChanged();
    partial void OndizhiChanging(string value);
    partial void OndizhiChanged();
    partial void OndianhuaChanging(string value);
    partial void OndianhuaChanged();
    partial void Onyouxiao_rq_xkChanging(System.Nullable<System.DateTime> value);
    partial void Onyouxiao_rq_xkChanged();
    #endregion
		
		public Gsp_shouying_qyshb()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xuhao", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int xuhao
		{
			get
			{
				return this._xuhao;
			}
			set
			{
				if ((this._xuhao != value))
				{
					this.OnxuhaoChanging(value);
					this.SendPropertyChanging();
					this._xuhao = value;
					this.SendPropertyChanged("xuhao");
					this.OnxuhaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_daima", DbType="VarChar(11)")]
		public string daima
		{
			get
			{
				return this._daima;
			}
			set
			{
				if ((this._daima != value))
				{
					this.OndaimaChanging(value);
					this.SendPropertyChanging();
					this._daima = value;
					this.SendPropertyChanged("daima");
					this.OndaimaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mingcheng", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string mingcheng
		{
			get
			{
				return this._mingcheng;
			}
			set
			{
				if ((this._mingcheng != value))
				{
					this.OnmingchengChanging(value);
					this.SendPropertyChanging();
					this._mingcheng = value;
					this.SendPropertyChanged("mingcheng");
					this.OnmingchengChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dizhi", DbType="VarChar(60)")]
		public string dizhi
		{
			get
			{
				return this._dizhi;
			}
			set
			{
				if ((this._dizhi != value))
				{
					this.OndizhiChanging(value);
					this.SendPropertyChanging();
					this._dizhi = value;
					this.SendPropertyChanged("dizhi");
					this.OndizhiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dianhua", DbType="VarChar(30)")]
		public string dianhua
		{
			get
			{
				return this._dianhua;
			}
			set
			{
				if ((this._dianhua != value))
				{
					this.OndianhuaChanging(value);
					this.SendPropertyChanging();
					this._dianhua = value;
					this.SendPropertyChanged("dianhua");
					this.OndianhuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_youxiao_rq_xk", DbType="DateTime")]
		public System.Nullable<System.DateTime> youxiao_rq_xk
		{
			get
			{
				return this._youxiao_rq_xk;
			}
			set
			{
				if ((this._youxiao_rq_xk != value))
				{
					this.Onyouxiao_rq_xkChanging(value);
					this.SendPropertyChanging();
					this._youxiao_rq_xk = value;
					this.SendPropertyChanged("youxiao_rq_xk");
					this.Onyouxiao_rq_xkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
